### ISSUE TITLE
app_swift doesn't speak any text

### ISSUE THREAD

**Issue by klpgo** [darrensessions/app_swift#3]
Subroutine app_exec() doesn't seem to work. Variable argv is initialized with 0, but no data copied into. Therefore ast_strlen_zero(text) is always true and message "%s requires text to speak!" is reported. 

Thanks,
Klaus

**Comment by sprior** [comment]
I've got the same issue - Cepstral Allison ver 5.1 voice, Asterisk 1.8, 6 4bit system.

**Comment by sprior** [comment]
If you go back in the git history and revert to commit "Merge pull request #1 from mojolingo/master and build the asterisk1.8 directory that's still there it should work (just did for me).  It looks like the merged version screwed up the code - I checked and that merged code doesn't even seem to make the call to parse its arguments.

**Comment by jkister** [comment]
might want to try my fork, not sure if darren is keeping up with this code.

FYI, i have _just_ gotten my fork running, seems to behave on Asterisk 11 and Asterisk 1.8.  it's probably broken on 1.4/1.6.   git://github.com/jkister/app_swift.git

**Comment by klpgo** [comment]
Hi Jeremy,

thanks for the link. I’ll give it a try.

Thanks,

Klaus 

Klaus Gottschalk

0711-7286943

Klaus.gottschalk@kgem.de

**Comment by klpgo** [comment]
Hi Jeremy,

thanks, it works. Had to add some linker options for asterisk version 1.8.20, otherwise the module did not load. See this article for the solution http://www.j-mb.de/blog/tag/undefined-symbol-swift_port_close/.

Thanks,

Klaus
