### ISSUE TITLE
DEBUG messages appear in asterisk CLI regardless of verbosity or debug level

### ISSUE THREAD

**Issue by paulgithub** [darrensessions/app_swift#7]
All DEBUG messages appear in asterisk CLI even when the verbosity and debug levels are set to 0.

This fills up the asterisk log files with information that makes debugging other issues a lot more difficult.

I believe this is the case because the app_swift.c has debug statements with no checks check for option_verbose or option_debug prior to the ast_log(LOG_DEBUG, ...) statement.

I added a check to a number of these e.g.:

if (option_verbose && option_debug > 3) {
    ast_log(LOG_DEBUG, "Easy read; %d bytes and %d at end, %d free\n", len, availatend, cfg_buffer_size - ps->qc);
}

This removed the DEBUG message but this had an adverse affect on picking up the DTMF variable in the dial plan (less likely to set the variable when a digit was pressed).

I am using:
CentOs release 6.4 (Final) 64-bit
Asterisk 11.5.1 64-bit
Cepstral_David-8kHz_x86-64-linux_6.0.1
app_swift latest version downloaded from https://github.com/darrensessions/app_swift

Have you any ideas what can be done to reduce the DEBUG messages but still use the DTMF feature.

Put another way everything works as is but there are too many DEBUG messages generated.

Thanks,
Paul

**Comment by YahirAlejandro** [comment]
Hey! Same problem here!

It's REALLY annoying and hard to read the CLI with all this debug stuff, so, where do you put that code to set the verbose off.

I don't care about DTMF right now, I just want to get rid of that logs.

Thanks in advance!

**Comment by paulgithub** [comment]
The easiest way is to edit the source file (app_swift.c) and search for ast_log and just comment out those that you do not want using /_ast_log(...)_/ and recompiling.

**Comment by paulgithub** [comment]
Sorry above comment should have had a slash followed by asterisk at beginning of comment and asterisk followed by slash at the end of the comment (standard c comment). The asterisks did not show for some reason.

**Comment by YahirAlejandro** [comment]
Hey! thanks a lot!

I'm going to give it a try.

Thank you.

**Comment by paulgithub** [comment]
This is actually not a problem with app_swift but the configuration on the Asterisk / FreePBX I was running app_swift on. It had a custom logger set in FreePBX (Settings -> Asterisk Logfile Settings) changing these (turing certain things off e.g. Debug) solved this problem.

Sorry for any problems caused by filing this issue
